### ISSUE TITLE
Question - High secret creation time

### ISSUE THREAD

**Issue by invin12** [isindir/sops-secrets-operator#135]
Hi everybody, 
As I notice it takes  about 4 minutes from deployment to real secret creation. Is it possible to reduce this time? In logs I saw that  
sops-secrets-operator refresh secret state once per 2 minutes, can I reduce this interval?

Example
Deployment time -
`
Sun 14 May 2023 03:31:31 PM UTC 
`

Simple bash loop -
`
while true; do date; k get secrets; sleep 5; done
`
```
Sun 14 May 2023 03:31:43 PM UTC
No resources found in grafana namespace.
...
...
Sun 14 May 2023 03:33:23 PM UTC <-- 2 minutes after deployment
NAME          TYPE     DATA   AGE
grafana-ini   Opaque   0      0s <--Why zero secrets???
...
...
Sun 14 May 2023 03:35:24 PM UTC <-- 4 minutes after deployment
NAME          TYPE     DATA   AGE
grafana-ini   Opaque   1      2m1s <--secret is created! But after 4 minutes(
```

**Comment by isindir** [comment]
Hi @invin12, default reconciliation loop re-queue period is 5 minutes:
https://github.com/isindir/sops-secrets-operator/blob/master/chart/helm3/sops-secrets-operator/values.yaml#L45

But the issue described does not look like related to this setting. It is difficult to say why it is happening without troubleshooting on the given environment. The operator should react on event of Create/Delete/Update of the given SopsSecret. I'd say it is likely that your system or operator is starving on some of the resources - most likely CPU. How many nodes do you have in your cluster, how many SopsSecrets are managed, what CPU/Memory allocation do you have in the cluster and for operator, etc - all may be contributing factors to the delays.

**Comment by invin12** [comment]
I think I find what a problem -
my .sops.yaml include hc_vault entries
```
creation_rules:
- path_regex: ".+.yaml|.+.ldif|.+.txt"
  encrypted_regex: ^data|^stringData
  key_groups:
  - age:
    - age1tmfjghjgu87hkjhkjhjkhytbn8wrfdswv2l7u4v6j5pq07txjv
    hc_vault:
    - https://my-vault-server-1/v1/sops/keys/secondkey
    - https://my-vault-server-2/v1/sops/keys/firstkey
```
And there was a network policy that blocked traffic from sops-operator to vault. When I changed it, secrets was created immediately. Thank You for support!
