### ISSUE TITLE
Error whilst reconciling AWS KMS on AWS EKS

### ISSUE THREAD

**Issue by adamstirk-ct** [isindir/sops-secrets-operator#15]
Hi,

I'm getting the error below whilst reconciling a secret encrypted with AWS KMS on AWS EKS.

```
2020-08-21T10:09:30.712905125Z 2020-08-21T10:09:30.712Z	INFO	controller-runtime.metrics	metrics server is starting to listen	{"addr": ":8080"}
2020-08-21T10:09:30.712994983Z 2020-08-21T10:09:30.712Z	INFO	setup	starting manager
2020-08-21T10:09:30.713190740Z I0821 10:09:30.713121       1 leaderelection.go:242] attempting to acquire leader lease  sops/ca57d051.github.com...
2020-08-21T10:09:30.713254686Z 2020-08-21T10:09:30.713Z	INFO	controller-runtime.manager	starting metrics server	{"path": "/metrics"}
2020-08-21T10:09:48.125626592Z I0821 10:09:48.125521       1 leaderelection.go:252] successfully acquired lease sops/ca57d051.github.com
2020-08-21T10:09:48.126085058Z 2020-08-21T10:09:48.125Z	DEBUG	controller-runtime.manager.events	Normal	{"object": {"kind":"ConfigMap","namespace":"sops","name":"ca57d051.github.com","uid":"561311e1-bca5-4ac7-bc98-ab430cd2ae6b","apiVersion":"v1","resourceVersion":"2399122"}, "reason": "LeaderElection", "message": "sops-secrets-operator-749d9cf67f-bxd2w_b0ba75d6-3cd6-4a3a-b774-70a78d21cacf became leader"}
2020-08-21T10:09:48.126385282Z 2020-08-21T10:09:48.126Z	INFO	controller-runtime.controller	Starting EventSource	{"controller": "sopssecret", "source": "kind source: /, Kind="}
2020-08-21T10:09:48.226947151Z 2020-08-21T10:09:48.226Z	INFO	controller-runtime.controller	Starting Controller	{"controller": "sopssecret"}
2020-08-21T10:09:48.226979105Z 2020-08-21T10:09:48.226Z	INFO	controller-runtime.controller	Starting workers	{"controller": "sopssecret", "worker count": 1}
2020-08-21T10:09:48.227042857Z 2020-08-21T10:09:48.226Z	INFO	controllers.SopsSecret	Reconciling SopsSecret
2020-08-21T10:09:48.227915583Z 2020-08-21T10:09:48.227Z	INFO	controllers.SopsSecret	Failed to Decrypt encrypted sops secret instance.
2020-08-21T10:09:48.227931973Z 2020-08-21T10:09:48.227Z	INFO	controllers.SopsSecret	Decryption error.
2020-08-21T10:09:48.227999845Z 2020-08-21T10:09:48.227Z	ERROR	controller-runtime.controller	Reconciler error	{"controller": "sopssecret", "request": "sops/example-sopssecret", "error": "Error getting data key: 0 successful groups required, got 0"}
2020-08-21T10:09:48.228011217Z github.com/go-logr/zapr.(*zapLogger).Error
2020-08-21T10:09:48.228014966Z 	/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
2020-08-21T10:09:48.228018656Z sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
2020-08-21T10:09:48.228022300Z 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:258
2020-08-21T10:09:48.228026016Z sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
2020-08-21T10:09:48.228029555Z 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:232
2020-08-21T10:09:48.228032976Z sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
2020-08-21T10:09:48.228036456Z 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:211
2020-08-21T10:09:48.228065480Z k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
2020-08-21T10:09:48.228070288Z 	/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:152
2020-08-21T10:09:48.228073825Z k8s.io/apimachinery/pkg/util/wait.JitterUntil
2020-08-21T10:09:48.228077153Z 	/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:153
2020-08-21T10:09:48.228080670Z k8s.io/apimachinery/pkg/util/wait.Until
2020-08-21T10:09:48.228084019Z 	/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:88
```

My kubernetes configuration is:

```
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: sops
  name: sops

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.5
  name: sopssecrets.isindir.github.com
spec:
  additionalPrinterColumns:
    - JSONPath: .status.msg
      name: Status
      type: string
  group: isindir.github.com
  names:
    kind: SopsSecret
    listKind: SopsSecretList
    plural: sopssecrets
    shortNames:
      - sops
    singular: sopssecret
  scope: Namespaced
  subresources: {}
  validation:
    openAPIV3Schema:
      description: SopsSecret is the Schema for the sopssecrets API
      properties:
        apiVersion:
          description:
            'APIVersion defines the versioned schema of this representation of an object. Servers should convert
            recognized schemas to the latest internal value, and may reject unrecognized values. More info:
            https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description:
            'Kind is a string value representing the REST resource this object represents. Servers may infer this from
            the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info:
            https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        sops:
          description: SopsMetadata defines the encryption details
          properties:
            azure_kv:
              description: AzureKms configuration
              items:
                description: AzureKmsItem defines Azure Keyvault Key specific encryption details
                properties:
                  created_at:
                    type: string
                  enc:
                    type: string
                  name:
                    type: string
                  vault_url:
                    type: string
                  version:
                    type: string
                type: object
              type: array
            encrypted_suffix:
              description: EncryptedSuffix - sops setting
              type: string
            gcp_kms:
              description: GcpKms configuration
              items:
                description: GcpKmsDataItem defines GCP KMS Key specific encryption details
                properties:
                  created_at:
                    type: string
                  enc:
                    type: string
                  resource_id:
                    type: string
                type: object
              type: array
            kms:
              description: AwsKms configuration
              items:
                description: KmsDataItem defines AWS KMS specific encryption details
                properties:
                  arn:
                    description: Arn - KMS key ARN to use
                    type: string
                  aws_profile:
                    type: string
                  created_at:
                    type: string
                  enc:
                    type: string
                type: object
              type: array
            lastmodified:
              description: LastModified - sops setting
              type: string
            mac:
              description: Mac - sops setting
              type: string
            pgp:
              description: Pgp configuration
              items:
                description: PgpDataItem defines PGP specific encryption details
                properties:
                  created_at:
                    type: string
                  enc:
                    type: string
                  fp:
                    description: FingerPrint - PGP FingerPrint to encrypt for
                    type: string
                type: object
              type: array
            version:
              description: Version - sops setting
              type: string
          type: object
        spec:
          description: SopsSecretSpec defines the desired state of SopsSecret
          properties:
            secretTemplates:
              description: SecretsTemplate is a list of secret templates to create Kubernetes Secrets
              items:
                description: SopsSecretTemplate defines the map of secrets to create
                properties:
                  annotations:
                    additionalProperties:
                      type: string
                    type: object
                  data:
                    additionalProperties:
                      type: string
                    description: Data is data map to use in Kubernetes secret
                    type: object
                  labels:
                    additionalProperties:
                      type: string
                    description: Labels to apply to Kubernetes secret
                    type: object
                  name:
                    description: Name is a name of the Kubernetes secret to create
                    type: string
                  type:
                    description: Kubernetes secret type
                    type: string
                required:
                  - data
                  - name
                type: object
              minItems: 1
              type: array
          required:
            - secretTemplates
          type: object
        status:
          description: SopsSecretStatus defines the observed state of SopsSecret
          properties:
            msg:
              description: Message - SopsSecret status message
              type: string
          type: object
      type: object
  version: v1alpha2
  versions:
    - name: v1alpha2
      served: true
      storage: true
status:
  acceptedNames:
    kind: ''
    plural: ''
  conditions: []
  storedVersions: []

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    name: sops-secrets-operator
  name: sops-secrets-operator
  namespace: sops

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sops-secrets-operator
  labels:
    name: sops-secrets-operator
rules:
  - apiGroups:
      - ''
    resources:
      - pods
      - services
      - services/finalizers
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - '*'
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - create
  - apiGroups:
      - apps
    resourceNames:
      - sops-secrets-operator
    resources:
      - deployments/finalizers
    verbs:
      - update
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - replicasets
    verbs:
      - get
  - apiGroups:
      - isindir.github.com
    resources:
      - '*'
    verbs:
      - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sops-secrets-operator
  labels:
    name: sops-secrets-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sops-secrets-operator
subjects:
  - kind: ServiceAccount
    name: sops-secrets-operator
    namespace: sops

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sops-secrets-operator
  namespace: sops
  labels:
    name: sops-secrets-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sops-secrets-operator
  template:
    metadata:
      labels:
        name: sops-secrets-operator
    spec:
      serviceAccountName: sops-secrets-operator
      containers:
        - name: sops-secrets-operator
          image: 'isindir/sops-secrets-operator:0.1.0'
          imagePullPolicy: Always
          command:
            - /usr/local/bin/manager
          args:
            #- "--metrics-addr=127.0.0.1:8080"
            - '--enable-leader-election'
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
```

To give permissions to AWS EKS to be able to decrypt the secret I have created the policy below.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "kms:Decrypt",
                "kms:Encrypt",
                "kms:DescribeKey",
                "kms:ReEncrypt*",
                "kms:GenerateDataKey*"
            ],
            "Resource": "arn:aws:kms:<awsRegion>:<organsiationId>:key/<kmsKeyId>"
        }
    ]
}
```

And given kubernetes permission by doing the following

```
eksctl utils associate-iam-oidc-provider --cluster=<clusterName>
eksctl create iamserviceaccount --cluster=<clusterName> --name=sops-secrets-operator --namespace=sops --attach-policy-arn=arn:aws:iam::<organsiationId>:policy/<policyName>
```

Doing some testing I have managed to get it to decrypt the secret by updating the Docker image to include the package "ca-certificates" package and removing the "nonroot" user and group and running the container as "root". The Dockerfile that is working for me is below.

```
# Build the manager binary
FROM golang:1.14.7 as builder

WORKDIR /workspace
# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum
# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN go mod download

# Copy the go source
COPY main.go main.go
COPY api/ api/
COPY controllers/ controllers/

# Build
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on go build -a -o manager main.go

# Use distroless as minimal base image to package the manager binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
FROM debian:buster

RUN apt-get -y update \
      && apt-get -y upgrade \
          && apt-get -y install --no-install-recommends gnupg2 ca-certificates \
          && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/local/bin
COPY --from=builder /workspace/manager .

ENTRYPOINT ["/usr/local/bin/manager"
```
