### ISSUE TITLE
Example for using Encryption with Vault Transit engine

### ISSUE THREAD

**Issue by linuxbsdfreak** [isindir/sops-secrets-operator#150]
Is there an example of using the operator with vault transit engine ? 

https://github.com/getsops/sops#encrypting-using-hashicorp-vault

**Comment by isindir** [comment]
@linuxbsdfreak, I think setting env variables should be sufficient, can you please try ?

**Comment by linuxbsdfreak** [comment]
Can you provide me an example for configuring via the values.yaml of the operator helm chart ?

**Comment by isindir** [comment]
Example below is from my RPI cluster to configure sops using `age`:

```
extraEnv:
- name: SOPS_AGE_KEY_FILE
  value: /etc/age/key.txt
...
secretsAsEnvVars:
- name: SOPS_AGE_RECIPIENTS
  secretKey: recipients
  secretName: sops-age
secretsAsFiles:
- mountPath: /etc/age
  name: age-key
  secretName: sops-age
```
