### ISSUE TITLE
In security context is capabilities NET_BIND_SERVICE needed?

### ISSUE THREAD

**Issue by twingate-blee** [isindir/sops-secrets-operator#179]
Is the capabilities NET_BIND_SERVICE needed?

To pass the pod security policy
```
kubectl label --dry-run=server --overwrite ns sops \
   pod-security.kubernetes.io/enforce=restricted \
   pod-security.kubernetes.io/enforce-version=latest
```

I would like to change the security context to 
```
    capabilities:
      drop:
        - all
```

vs

```
    capabilities:
      drop:
        - all
      add:
        - NET_BIND_SERVICE
```
