### ISSUE TITLE
Data keys removed from SopsSecret not removed from generated Secret

### ISSUE THREAD

**Issue by albertrdixon** [isindir/sops-secrets-operator#31]
If I remove a data key from a secret template, the key does not seem to be removed from an already existing secret.

## reproduce

1. Create `SopsSecret` with a template with 2 keys
    ```
      secretTemplates:
        - name: example
          data:
             foo: bar
             bif: baz
    ```
2. Apply to cluster and wait for secret to be created
3. Remove `bif: baz` from `SopsSecret`
4. Apply updated manifest

## expected outcome

Data keys removed from `SopsSecret` are also removed from generated `Secret`s
