### ISSUE TITLE
Deleted secrets generated from SopsSecret are not recreated

### ISSUE THREAD

**Issue by pdreker** [isindir/sops-secrets-operator#35]
When one generates secrets from a SopsSecret CR and then deletes the resulting secret, the deleted secret is not recreated by the operator. In my view this is unexpected as most (all?) other generated resources are reinstated/recreated after their deletion (think: deleting a Pod from a Deployment immediately recreates the Pod).

To reproduce:
* create a SopsSecret CR and wait for operator to reconcile
* delete the secret created by the operator

Result:
Secret is deleted and remains deleted and is not recreated

Expected Result: Secret is recreated from SopsSecret.

**Comment by isindir** [comment]
@pdreker, that is indeed unexpected behaviour, I need to test it more closely. Is that the case as well, when sopssecrets contains only one secret template?

**Comment by pdreker** [comment]
I have a testsecret containing 3 Secrets (only random values, so no information leak), which I will paste below. Encrypt it using SOPS and `kubectl apply -f` it into a cluster. Then delete one of the resulting secrets to reproduce.

```yaml
apiVersion: isindir.github.com/v1alpha2
kind: SopsSecret
metadata:
  name: example-sopssecret
spec:
  secretTemplates:
    - name: jenkins-secret
      labels:
        "jenkins.io/credentials-type": "usernamePassword"
      annotations:
        "jenkins.io/credentials-description" : "credentials from Kubernetes"
      data:
        username: myUsername
        password: 'Pa885word'
    - name: some-token
      data:
        token: Wb4ziZdELkdUf6m6KtNd7iRjjQRvSeJno5meH4NAGHFmpqJyEsekZ2WjX232s4Gj
    - name: docker-login
      type: 'kubernetes.io/dockerconfigjson'
      data:
        .dockerconfigjson: '{"auths":{"index.docker.io":{"username":"imyuser","password":"mypass","email":"myuser@example.com","auth":"aW15dXNlcjpteXBhc3M="}}}'
```

**Comment by pdreker** [comment]
Also happens, when there is only one template in the SopsSecret.

```yaml
apiVersion: isindir.github.com/v1alpha2
kind: SopsSecret
metadata:
  name: example-sopssecret
spec:
  secretTemplates:
    - name: jenkins-secret-single
      labels:
        "jenkins.io/credentials-type": "usernamePassword"
      annotations:
        "jenkins.io/credentials-description" : "credentials from Kubernetes"
      data:
        username: myUsername
        password: 'Pa885word'
```
