### ISSUE TITLE
0.1.9 - error in kustomize configuration for entrypoint

### ISSUE THREAD

**Issue by so0k** [isindir/sops-secrets-operator#47]
Seems the manager deploy manifest has wrong entrypoint:

```
  Normal   Pulled     11s (x2 over 12s)  kubelet, ...  Container image "isindir/sops-secrets-operator:0.1.9" already present on machine
  Normal   Created    11s (x2 over 12s)  kubelet, ...  Created container manager
  Warning  Failed     10s (x2 over 12s)  kubelet, ...  Error: failed to start container "manager": Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "/manager": stat /manager: no such file or directory: unknown
```

Fix for `0.1.9`:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: controller
  newName: isindir/sops-secrets-operator
  newTag: 0.1.9

namespace: sops-secrets-operator-system

bases:
- github.com/isindir/sops-secrets-operator/config/default/?ref=0.1.9

patches:
  - target:
      kind: Deployment
      name: sops-secrets-operator-controller-manager
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/1/command
        value: [ /usr/local/bin/manager ]
```

**Comment by so0k** [comment]
Another fix if you're using EKS IAM, need to patch fsGroup

```
      - op: add
        path: /spec/template/spec/securityContext
        value:
          fsGroup: 1000
```

**Comment by so0k** [comment]
I could try and do a PR, but I'm handling it through kustomize for now

for others moving to server side applies, need to add the `protocol` to the ports  see: https://github.com/kubernetes-sigs/structured-merge-diff/issues/130:

```yaml
patches:
  - target:
      kind: Deployment
      name: sops-secrets-operator-controller-manager
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/ports/0/protocol
        value: TCP
  - target:
      kind: Service
      name: sops-secrets-operator-controller-manager-metrics-service
    patch: |-
      - op: add
        path: /spec/ports/0/protocol
        value: TCP
```
