### ISSUE TITLE
Possibility to pass SopsSecret labels to generated k8s secret

### ISSUE THREAD

**Issue by lmolas** [isindir/sops-secrets-operator#58]
Hello,

It would be nice to pass labels from SopsSecret to generated kubernetes secret.

Thx

**Comment by isindir** [comment]
Hi @lmolas , it should be possible, please see:
https://github.com/isindir/sops-secrets-operator/blob/master/api/v1alpha2/sopssecret_types.go#L21
BR

**Comment by lmolas** [comment]
Yes i know it is the same for all kubernetes resources. I have tried to put custom labels and would like to retrieve those labels in the generated kubernetes secret: the regular one generated by the operator, not only the SopsSecret.

**Comment by isindir** [comment]
That should be possible, if not there is bug which preventing it:

```
apiVersion: isindir.github.com/v1alpha2
kind: SopsSecret
metadata:
  name: example-sopssecret
spec:
  secretTemplates:
    - name: jenkins-secret
      labels:
        "jenkins.io/credentials-type": "usernamePassword"
      annotations:
        "jenkins.io/credentials-description" : "credentials from Kubernetes"
      data:
        username: myUsername
        password: 'Pa$$word'
```

In the example above labels and annotations of the secret template must be applied to the resulting secret. **Note**, that these are not defined in SopsSecret metadata.

Please test this behaviour and if these are not applied, fetch relevant logs from the operator and post here. Thanks
