### ISSUE TITLE
validation error

### ISSUE THREAD

**Issue by mmclane** [isindir/sops-secrets-operator#93]
I was trying out this operator today and I get a validation error when I apply.  Here are the steps I took.

1. Copied the example our of the readme and save it to secret3.yaml
```
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: example-sopssecret
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: my-secret-name-1
          labels:
            label1: value1
          annotations:
            key1: value1
          stringData:
            data-name0: data-value0
          data:
            data-name1: ZGF0YS12YWx1ZTE=
        - name: jenkins-secret
          labels:
            jenkins.io/credentials-type: usernamePassword
          annotations:
            jenkins.io/credentials-description: credentials from Kubernetes
          stingData:
            username: myUsername
            password: Pa$$word
        - name: some-token
          stringData:
            token: Wb4ziZdELkdUf6m6KtNd7iRjjQRvSeJno5meH4NAGHFmpqJyEsekZ2WjX232s4Gj
        - name: docker-login
          type: kubernetes.io/dockerconfigjson
          stringData:
            .dockerconfigjson: '{"auths":{"index.docker.io":{"username":"imyuser","password":"mypass","email":"myuser@abc.com","auth":"aW15dXNlcjpteXBhc3M="}}}'
```
2. Ran the following command to encrypt it with sops.  File content included
```
> sops -e -i --encrypted-suffix='Data' Secret3.yaml
```
```
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: example-sopssecret
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: my-secret-name-1
          labels:
            label1: value1
          annotations:
            key1: value1
          stringData:
            data-name0: ENC[AES256_GCM,data:4o1Xc+++OWwtHAY=,iv:UsMW/iPGTY5reLzp8Jhzgv5Gwi8XFuPro1eMyVZShc8=,tag:WbRAUcchnPM6Qvlle9B7FA==,type:str]
          data:
            data-name1: ZGF0YS12YWx1ZTE=
        - name: jenkins-secret
          labels:
            jenkins.io/credentials-type: usernamePassword
          annotations:
            jenkins.io/credentials-description: credentials from Kubernetes
          stingData:
            username: ENC[AES256_GCM,data:CEgSYbYpdvikoQ==,iv:EJjsdWpFNq+75GhA/RDh6kfQUVL78VGKscLH9RdS9gg=,tag:SycroJf/kPtspAvxWI/LkA==,type:str]
            password: ENC[AES256_GCM,data:OYpFzJvNcys=,iv:1lo55np8EWledb32UqtEnpgI2mZpgjVPgl9+c24Egy8=,tag:cRroYKkgt3+h+PDyI2dGLg==,type:str]
        - name: some-token
          stringData:
            token: ENC[AES256_GCM,data:Xt8mAuqc+mGQegoMeyo6zD95FIB955uB6Hzd4XKUnoVe3LuyXhczR9JcAT/L2AHWqyzrDzEokNlmmyB3yjfLgg==,iv:mqh+t36KOKcvtHnmd0PyrLQHWbFgAmCPYrywFGZ41VQ=,tag:qRip2eqUtvF86nfkwhLYbw==,type:str]
        - name: docker-login
          type: kubernetes.io/dockerconfigjson
          stringData:
            .dockerconfigjson: ENC[AES256_GCM,data:BNCHUQj4sPETQYJj1ES7+u5PzG9cmv0y7J9mnftsjOcnF9pat25V7A2JuHtCZUHEP3wgY9l/2zKmOBgAncUcTzfKpRFOUxJJmOrwkROMtV5Q0p4X47BBWt/4XrkqWjHZUEQ2D2V4M/ALDO0cUmDxQZwCO+snDDjn5XZPognSVg==,iv:U1ig1YJ21FX2zHV2TLQV0d0ydMUSoz+11IftB/aAxsg=,tag:hQDnu89gPO5mn0X81y4V/w==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:878788551012:key/284bf172-5a83-47a7-9ab6-d40f3e261b34
          role: arn:aws:iam::878788551012:role/sops
          created_at: "2021-11-24T19:59:39Z"
          enc: AQICAHivP1FSTpPIgf1yuRF2Q0j1SvqpBAgYtWSJZkc9vkpYeQGAOcoIsUMuUKSCLdx+ejVcAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMeszeo69SvoNQyy9GAgEQgDsSO4W5r6UfuVa4NfwAlLAiBRbcSCR5cbci55VzPjHExzbN8QO1KIWes6b1cfInfR9AM0QQ2sBIkmxuPw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-24T19:59:39Z"
    mac: ENC[AES256_GCM,data:4ZQ/ctpMBqrv+GUEGT+7zFlmxpclHCIvT1swOTUrdN4KVQ62RbNZvEZYHAUu4Gy5tNMrTiK4OObAmv0bzvV1ZtS4VRFEdSglDmaxKonejcbklI+IuhykPXP7y+KkjMfwyVXYP2Ms1CJtKluhWLmfJ5NF3RfYYpBULypc794d3MY=,iv:8Ac93UK8p61dZd8hauuXA8g4krLhOKlYVrkD6ofUI7w=,tag:OsP7j/gXPVigMr3ox4fNpA==,type:str]
    pgp: []
    encrypted_suffix: Data
    version: 3.7.1
```

3. Ran the following command to apply but I get an error
```
kc apply -f Secret3.yaml
error: error validating "Secret3.yaml": error validating data: ValidationError(SopsSecret.spec.secretTemplates[1]): unknown field "stingData" in com.github.isindir.v1alpha3.SopsSecret.spec.secretTemplates; if you choose to ignore these errors, turn validation off with --validate=false
```

If I include the --validate=false it applies successfully and the operator works and the secrets are created.  But I really shouldn't need to include --validate=false should I?
